export const GET_EVENTS = "GET_EVENTS";
export const GET_EVENTS_SUCCESS = "GET_EVENTS_SUCCESS";
export const GET_EVENTS_FAILURE = "GET_EVENTS_FAILURE";

export const CREATE_EVENT = "CREATE_EVENT";
export const CREATE_EVENT_SUCCESS = "CREATE_EVENT_SUCCESS";
export const CREATE_EVENT_FAILURE = "CREATE_EVENT_FAILURE";

export const UPDATE_ATTENDANCE = "UPDATE_ATTENDANCE";
export const UPDATE_ATTENDANCE_SUCCESS = "UPDATE_ATTENDANCE_SUCCESS";
export const UPDATE_ATTENDANCE_FAILURE = "UPDATE_ATTENDANCE_FAILURE";

export const UPDATE_PAYMENT = "UPDATE_PAYMENT";
export const UPDATE_PAYMENT_SUCCESS = "UPDATE_PAYMENT_SUCCESS";
export const UPDATE_PAYMENT_FAILURE = "UPDATE_PAYMENT_FAILURE";

export const ASSIGN_TEAM = "ASSIGN_TEAM";
export const ASSIGN_TEAM_SUCCESS = "ASSIGN_TEAM_SUCCESS";
export const ASSIGN_TEAM_FAILURE = "ASSIGN_TEAM_FAILURE";

export const UPLOAD_EVENT_MEDIA = "UPLOAD_EVENT_MEDIA";
export const UPLOAD_EVENT_MEDIA_SUCCESS = "UPLOAD_EVENT_MEDIA_SUCCESS";
export const UPLOAD_EVENT_MEDIA_FAILURE = "UPLOAD_EVENT_MEDIA_FAILURE";

export const CLOSE_EVENT = "CLOSE_EVENT";
export const CLOSE_EVENT_SUCCESS = "CLOSE_EVENT_SUCCESS";
export const CLOSE_EVENT_FAILURE = "CLOSE_EVENT_FAILURE";